language: generic 
sudo: required
services:
  - docker

before_install: 
  - docker build -t frontend-image -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true frontend-image npm run test

after_success: 
  - docker build -t sashakarpiv09/multi-client ./client
  - docker build -t sashakarpiv09/multi-nginx ./nginx
  - docker build -t sashakarpiv09/multi-server ./server
  - docker build -t sashakarpiv09/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sashakarpiv09/multi-client
  - docker push sashakarpiv09/multi-nginx
  - docker push sashakarpiv09/multi-server
  - docker push sashakarpiv09/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-125309283773"
  bucket_path: "multi-docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  skip_cleanup: true